name: Docs Checker

on: 
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build_check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v1
    
    - name: Search and Compiles Latex Files
      uses: Jatus93/Latex-multicompiler@v1.0
      with:
        path_to_list: .github/filesList
        artifact: true
    
    - name: GulpeaseCheck
      uses: Jatus93/GulpeaseAction@master
      with:
        directory: Documents/
    
    - name: SpellCheck
      uses: Jatus93/spellCheck@master
      with:
        directory: ./Documents
        languages: "en_GB;en_US;italiano"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf-artifact
        path: Documents/ # path/to/artifact
    
